import Link from "next/link";

export const metadata = {
  title: "Disclaimer — 3S Stock Finder",
  description: "Important disclaimer and risk disclosure for 3S Stock Finder users.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50">
      <div className="bg-gradient-to-r from-slate-900 via-blue-900 to-indigo-900 text-white py-12 px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-extrabold mb-2">Disclaimer</h1>
          <p className="text-slate-300">Please read carefully before using this service.</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-10 space-y-6 text-slate-700 text-sm leading-relaxed">
        <section className="bg-amber-50 border border-amber-200 rounded-2xl p-5">
          <h2 className="font-bold text-amber-900 text-base mb-2">⚠ Not Investment Advice</h2>
          <p className="text-amber-800">
            3S Stock Finder is an AI-powered research and informational tool. Nothing on this platform constitutes investment advice, financial advice, trading advice, or any other sort of advice. The stock recommendations generated by this tool should not be relied upon as a basis for making investment decisions.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-slate-800 text-base mb-2">SEBI Registration</h2>
          <p>
            3S Stock Finder is <strong>not registered with the Securities and Exchange Board of India (SEBI)</strong> as an investment adviser, research analyst, or stock broker. The platform does not hold any SEBI registration and is not authorized to provide investment advice under the SEBI (Investment Advisers) Regulations, 2013 or the SEBI (Research Analysts) Regulations, 2014.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-slate-800 text-base mb-2">AI-Generated Content</h2>
          <p>
            All stock recommendations, analysis, confidence scores, and catalysts are generated by artificial intelligence models (Large Language Models). These outputs may be inaccurate, outdated, biased, or incomplete. AI models can hallucinate facts and may not reflect current market conditions, recent corporate events, or regulatory changes.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-slate-800 text-base mb-2">Risk Disclosure</h2>
          <p>
            Investments in equity markets are subject to market risk. Past performance is not indicative of future results. The value of investments may go up or down. You may lose some or all of your invested capital. Please consult a SEBI-registered investment adviser before making any investment decisions.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-slate-800 text-base mb-2">No Liability</h2>
          <p>
            3S Stock Finder and its creators accept no liability for any financial losses, damages, or consequences arising from the use of information provided on this platform. Use of this service is entirely at your own risk.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-slate-800 text-base mb-2">Data Sources</h2>
          <p>
            Price data is sourced from Yahoo Finance. News sentiment is derived from Google News RSS. Fundamental data may be delayed or incomplete. The platform does not guarantee the accuracy or timeliness of any data displayed.
          </p>
        </section>

        <div className="pt-4 flex gap-4">
          <Link href="/methodology" className="text-indigo-600 hover:underline font-medium">Read our Methodology →</Link>
          <Link href="/" className="text-slate-500 hover:underline">← Back to Home</Link>
        </div>
      </div>
    </div>
  );
}
